/*
 * Charuvi Learning Hub — Site Search
 * -----------------------------------
 * Self-injecting, no dependencies. Loads search-index.json (generated by
 * build-search-index.py), opens a modal overlay on ⌘K / Ctrl-K or "/",
 * scores candidate docs/headings, and renders live results.
 *
 * Drop `<script defer src="<path>/search.js"></script>` on any page.
 * The script resolves the index URL relative to its own <script> src,
 * so it works from any directory depth.
 */
(function () {
  "use strict";

  if (window.__CharuviSearchLoaded) return;
  window.__CharuviSearchLoaded = true;

  // ---------------------------------------------------------------- resolve paths
  // Where is this <script> on disk? Used to compute the JSON and result URLs.
  var thisScript = document.currentScript;
  if (!thisScript) {
    var scripts = document.getElementsByTagName("script");
    for (var i = scripts.length - 1; i >= 0; i--) {
      if (/search\.js(\?|$)/.test(scripts[i].src)) { thisScript = scripts[i]; break; }
    }
  }
  var scriptSrc = (thisScript && thisScript.src) || "";
  var ROOT_URL  = new URL(".", scriptSrc).href; // ends with /

  // ---------------------------------------------------------------- state
  var index = null;           // array of doc objects
  var indexPromise = null;    // single-flight fetch
  var isOpen = false;
  var activeIndex = 0;        // highlighted row
  var results = [];           // last-rendered result list

  // ---------------------------------------------------------------- UI build
  var css = ""; // populated once DOM is ready — actual styles live in styles.css
  var modal, panel, input, resultsEl, hintEl, emptyEl;

  function buildModal() {
    modal = document.createElement("div");
    modal.className = "search-modal";
    modal.setAttribute("hidden", "");
    modal.innerHTML =
      '<div class="search-panel" role="dialog" aria-modal="true" aria-label="Site search">' +
        '<div class="search-input-row">' +
          '<svg class="search-icon" viewBox="0 0 24 24" width="18" height="18" aria-hidden="true">' +
            '<circle cx="11" cy="11" r="7" fill="none" stroke="currentColor" stroke-width="2"/>' +
            '<line x1="16.5" y1="16.5" x2="21" y2="21" stroke="currentColor" stroke-width="2" stroke-linecap="round"/>' +
          '</svg>' +
          '<input class="search-input" type="text" autocomplete="off" spellcheck="false" ' +
            'placeholder="Search the learning hub — try &quot;backprop&quot;, &quot;P vs NP&quot;, &quot;entropy&quot;&hellip;" />' +
          '<button class="search-close" type="button" aria-label="Close search">ESC</button>' +
        '</div>' +
        '<div class="search-results" role="listbox"></div>' +
        '<div class="search-empty" hidden>' +
          '<p class="se-title">Type to search</p>' +
          '<p class="se-sub">Search titles, section headings, and body text across all three tracks.</p>' +
          '<div class="se-chips">' +
            '<span>try:</span>' +
            '<button type="button" data-q="backpropagation">backpropagation</button>' +
            '<button type="button" data-q="eigenvalue">eigenvalue</button>' +
            '<button type="button" data-q="P vs NP">P vs NP</button>' +
            '<button type="button" data-q="Bayes">Bayes</button>' +
            '<button type="button" data-q="transformer">transformer</button>' +
            '<button type="button" data-q="gradient descent">gradient descent</button>' +
          '</div>' +
        '</div>' +
        '<div class="search-footer">' +
          '<span><kbd>↑</kbd><kbd>↓</kbd> navigate</span>' +
          '<span><kbd>↵</kbd> open</span>' +
          '<span><kbd>esc</kbd> close</span>' +
          '<span class="sf-count"></span>' +
        '</div>' +
      '</div>';
    document.body.appendChild(modal);

    panel     = modal.querySelector(".search-panel");
    input     = modal.querySelector(".search-input");
    resultsEl = modal.querySelector(".search-results");
    emptyEl   = modal.querySelector(".search-empty");
    hintEl    = modal.querySelector(".sf-count");

    modal.addEventListener("click", function (e) {
      if (e.target === modal) close();
    });
    modal.querySelector(".search-close").addEventListener("click", close);
    input.addEventListener("input", onInput);
    input.addEventListener("keydown", onKeydown);

    // example-query chips
    emptyEl.querySelectorAll("button[data-q]").forEach(function (btn) {
      btn.addEventListener("click", function () {
        input.value = btn.getAttribute("data-q");
        onInput();
      });
    });
  }

  function buildTrigger() {
    // Floating trigger — visible in bottom-right on every page.
    var btn = document.createElement("button");
    btn.type = "button";
    btn.className = "search-trigger";
    btn.setAttribute("aria-label", "Search (⌘K)");
    btn.innerHTML =
      '<svg viewBox="0 0 24 24" width="16" height="16" aria-hidden="true">' +
        '<circle cx="11" cy="11" r="7" fill="none" stroke="currentColor" stroke-width="2"/>' +
        '<line x1="16.5" y1="16.5" x2="21" y2="21" stroke="currentColor" stroke-width="2" stroke-linecap="round"/>' +
      '</svg>' +
      '<span class="st-label">Search</span>' +
      '<kbd class="st-kbd">⌘K</kbd>';
    btn.addEventListener("click", open);
    document.body.appendChild(btn);

    // Also wire up any pre-existing `.search-trigger-inline` buttons in page chrome
    Array.prototype.forEach.call(
      document.querySelectorAll(".search-trigger-inline"),
      function (el) { el.addEventListener("click", open); }
    );
  }

  // ---------------------------------------------------------------- data
  // The index is supplied by search-index.js, which sets window.__charuviSearchIndex
  // to a {version,count,docs} object. Loading it via <script> keeps the whole site
  // static — no fetch(), no HTTP server, works on file://.
  function prepareIndex() {
    var payload = window.__charuviSearchIndex;
    if (!payload || !payload.docs) {
      console.error("[search] search-index.js not loaded — is <script src=search-index.js> present before search.js?");
      index = [];
      return index;
    }
    index = payload.docs;
    // precompute lowercased searchable fields
    index.forEach(function (d) {
      d._lt = (d.title || "").toLowerCase();
      d._ls = (d.subtitle || "").toLowerCase();
      d._lb = (d.body || "").toLowerCase();
      d._lh = (d.headings || []).map(function (h) {
        return { id: h.id, text: h.text, lc: (h.text || "").toLowerCase() };
      });
    });
    return index;
  }

  function ensureIndex() {
    if (index) return Promise.resolve(index);
    if (indexPromise) return indexPromise;
    indexPromise = Promise.resolve(prepareIndex());
    return indexPromise;
  }

  // ---------------------------------------------------------------- search
  // Short stop-words that drown the signal if we let them match body text.
  var STOP = { "a":1,"an":1,"the":1,"of":1,"in":1,"on":1,"to":1,"and":1,"or":1,"is":1,"it":1,"vs":1,"for":1,"by":1 };

  function tokenize(q) {
    // Keep single-char digits/letters out of matching — they match half the corpus.
    // But preserve them in the phrase match (doc._lt indexOf phrase) for queries like "P vs NP".
    return (q || "")
      .toLowerCase()
      .split(/[^a-z0-9]+/)
      .filter(function (t) { return t.length >= 2 && !STOP[t]; });
  }

  function scoreDoc(doc, phrase, tokens) {
    // weight map: title ≫ heading ≫ subtitle ≫ body
    var score = 0;
    var matchedHeading = null;

    // Full-phrase matches are a very strong signal — they catch short-word
    // queries like "P vs NP" that would otherwise be filtered by tokenizer.
    if (phrase && doc._lt.indexOf(phrase) !== -1) score += 80;
    if (phrase && doc._ls.indexOf(phrase) !== -1) score += 25;
    if (phrase && doc._lb.indexOf(phrase) !== -1) score += 15;
    if (phrase) {
      for (var hp = 0; hp < doc._lh.length; hp++) {
        if (doc._lh[hp].lc.indexOf(phrase) !== -1) {
          score += 35;
          if (!matchedHeading) matchedHeading = doc._lh[hp];
        }
      }
    }

    for (var i = 0; i < tokens.length; i++) {
      var t = tokens[i];

      // whole-word title match
      var titleRe = new RegExp("(^|[^a-z0-9])" + escapeRe(t) + "([^a-z0-9]|$)");
      if (titleRe.test(doc._lt)) score += 25;
      else if (doc._lt.indexOf(t) !== -1) score += 12; // prefix or substring

      if (doc._ls.indexOf(t) !== -1) score += 6;
      if (doc._lb.indexOf(t) !== -1) score += 2;

      // heading match — capture the best-matching heading so we can deep-link
      for (var h = 0; h < doc._lh.length; h++) {
        if (doc._lh[h].lc.indexOf(t) !== -1) {
          score += 10;
          if (!matchedHeading) matchedHeading = doc._lh[h];
        }
      }

      // terms-bag prefix bonus (catches word fragments)
      var terms = doc.terms || [];
      for (var k = 0; k < terms.length; k++) {
        if (terms[k].indexOf(t) === 0) { score += 1; break; }
      }
    }

    // kind adjustments — subjects/deep-dives usually win over hub pages
    if (doc.kind === "hub" || doc.kind === "track-hub") score -= 5;

    return { score: score, heading: matchedHeading };
  }

  function escapeRe(s) { return s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&"); }

  function search(query) {
    var q = (query || "").trim();
    if (!q) return [];

    var phrase = q.toLowerCase();
    var tokens = tokenize(q);
    if (!tokens.length) return [];

    var out = [];
    for (var i = 0; i < index.length; i++) {
      var r = scoreDoc(index[i], phrase, tokens);
      if (r.score > 0) {
        out.push({ doc: index[i], score: r.score, heading: r.heading });
      }
    }
    out.sort(function (a, b) {
      if (b.score !== a.score) return b.score - a.score;
      return a.doc.title.localeCompare(b.doc.title);
    });
    return out.slice(0, 18);
  }

  // ---------------------------------------------------------------- rendering
  function render(query) {
    results = search(query);
    activeIndex = 0;

    if (!query.trim()) {
      resultsEl.hidden = true;
      emptyEl.hidden = false;
      hintEl.textContent = "";
      return;
    }
    emptyEl.hidden = true;
    resultsEl.hidden = false;

    if (!results.length) {
      resultsEl.innerHTML = '<div class="search-no-results">' +
        '<p>No matches for <strong>' + escapeHtml(query) + '</strong>.</p>' +
        '<p class="snr-sub">Try a shorter word, or a different spelling.</p>' +
      '</div>';
      hintEl.textContent = "0 results";
      return;
    }

    var phrase = query.trim().toLowerCase();
    var tokens = tokenize(query);

    var html = results.map(function (r, idx) {
      var d = r.doc;
      var url = ROOT_URL + d.url;
      if (r.heading && r.heading.id) url += "#" + r.heading.id;

      var snippet = buildSnippet(d, tokens, phrase);
      var trackLabel = trackDisplay(d.track, d.kind);

      return '' +
        '<a class="search-result' + (idx === 0 ? " sr-active" : "") + '"' +
           ' href="' + url + '" role="option" data-idx="' + idx + '">' +
          '<span class="sr-track sr-track-' + d.track + '">' + trackLabel + '</span>' +
          '<div class="sr-main">' +
            '<div class="sr-title">' + highlight(d.title, tokens) + '</div>' +
            (r.heading
              ? '<div class="sr-heading">§ ' + highlight(r.heading.text, tokens) + '</div>'
              : "") +
            '<div class="sr-snippet">' + snippet + '</div>' +
          '</div>' +
        '</a>';
    }).join("");

    resultsEl.innerHTML = html;
    hintEl.textContent = results.length + " result" + (results.length === 1 ? "" : "s");

    // pointer interactions
    Array.prototype.forEach.call(resultsEl.querySelectorAll(".search-result"), function (el) {
      el.addEventListener("mouseenter", function () {
        setActive(parseInt(el.getAttribute("data-idx"), 10));
      });
    });
  }

  function trackDisplay(track, kind) {
    if (track === "ai-ml") return "AI/ML";
    if (track === "math")  return "MATH";
    if (track === "cs")    return "CS";
    return "HUB";
  }

  function buildSnippet(d, tokens, phrase) {
    var body = d.body || d.subtitle || "";
    if (!body) return "";

    var lower = body.toLowerCase();
    var idx = -1;

    if (phrase) idx = lower.indexOf(phrase);
    if (idx < 0) {
      for (var i = 0; i < tokens.length; i++) {
        idx = lower.indexOf(tokens[i]);
        if (idx >= 0) break;
      }
    }
    if (idx < 0) idx = 0;

    var start = Math.max(0, idx - 60);
    var end   = Math.min(body.length, idx + 160);
    var slice = body.slice(start, end);
    if (start > 0) slice = "… " + slice;
    if (end < body.length) slice = slice + " …";
    return highlight(slice, tokens);
  }

  function highlight(text, tokens) {
    if (!text) return "";
    var safe = escapeHtml(text);
    if (!tokens || !tokens.length) return safe;
    // match any token, longest first to avoid partial overlap
    var sorted = tokens.slice().sort(function (a, b) { return b.length - a.length; });
    var re = new RegExp("(" + sorted.map(escapeRe).join("|") + ")", "gi");
    return safe.replace(re, "<mark>$1</mark>");
  }

  function escapeHtml(s) {
    return String(s)
      .replace(/&/g, "&amp;")
      .replace(/</g, "&lt;")
      .replace(/>/g, "&gt;")
      .replace(/"/g, "&quot;");
  }

  // ---------------------------------------------------------------- navigation
  function setActive(i) {
    if (!results.length) return;
    activeIndex = (i + results.length) % results.length;
    var nodes = resultsEl.querySelectorAll(".search-result");
    nodes.forEach(function (el, idx) {
      el.classList.toggle("sr-active", idx === activeIndex);
      if (idx === activeIndex) {
        var r = el.getBoundingClientRect();
        var pr = resultsEl.getBoundingClientRect();
        if (r.bottom > pr.bottom) el.scrollIntoView({ block: "end" });
        else if (r.top < pr.top)  el.scrollIntoView({ block: "start" });
      }
    });
  }

  function openActive() {
    if (!results.length) return;
    var r = results[activeIndex];
    var url = ROOT_URL + r.doc.url;
    if (r.heading && r.heading.id) url += "#" + r.heading.id;
    window.location.href = url;
  }

  // ---------------------------------------------------------------- events
  function onInput() { render(input.value); }

  function onKeydown(e) {
    if (e.key === "ArrowDown")   { e.preventDefault(); setActive(activeIndex + 1); }
    else if (e.key === "ArrowUp"){ e.preventDefault(); setActive(activeIndex - 1); }
    else if (e.key === "Enter")  { e.preventDefault(); openActive(); }
    else if (e.key === "Escape") { e.preventDefault(); close(); }
  }

  function onGlobalKey(e) {
    var meta = e.metaKey || e.ctrlKey;
    if (meta && (e.key === "k" || e.key === "K")) {
      e.preventDefault();
      isOpen ? close() : open();
      return;
    }
    if (!isOpen && e.key === "/") {
      var tag = (document.activeElement && document.activeElement.tagName) || "";
      if (tag === "INPUT" || tag === "TEXTAREA" || document.activeElement.isContentEditable) return;
      e.preventDefault();
      open();
    }
    if (isOpen && e.key === "Escape") { close(); }
  }

  // ---------------------------------------------------------------- open/close
  function open() {
    ensureIndex().then(function () {
      if (!modal) buildModal();
      modal.removeAttribute("hidden");
      isOpen = true;
      document.body.classList.add("search-open");
      input.value = "";
      render("");
      setTimeout(function () { input.focus(); }, 10);
    });
  }

  function close() {
    if (!modal) return;
    modal.setAttribute("hidden", "");
    isOpen = false;
    document.body.classList.remove("search-open");
  }

  // ---------------------------------------------------------------- boot
  function boot() {
    buildTrigger();
    document.addEventListener("keydown", onGlobalKey);
    // warm the index shortly after load
    setTimeout(ensureIndex, 500);
  }

  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", boot);
  } else {
    boot();
  }

  // expose for manual opens
  window.CharuviSearch = { open: open, close: close };
})();
